# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/bq/sdm660-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter zangya zangyapro,$(TARGET_DEVICE)),)

endif
